### DISCUSSION TITLE
Port forwarding in docker

### DISCUSSION THREAD

**Discussion by FabienVINCENT** [eslint/config-inspector#68] [General]
Hello,

I run esling via Nuxt and docker but I have some issue ...

there is something too configure in docker ?

```
version: '3.7'

services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "7777:7777"
      - "8123:8123"
    volumes:
      - .:/app
    tty: true
    networks:
      - backend

networks:
  backend:
    external: true

```

![image](https://github.com/eslint/config-inspector/assets/68119797/b8b75ccc-b303-42d6-96bb-9a70e0ef6f59)
